version: "3.9"

services:
  db-spring:
    image: postgres
    environment:
      POSTGRES_DB: db-spring
      POSTGRES_PASSWORD: 123
    ports:
      - 5555:5432
    networks:
      jwt:

  spring-jwt:
    build:
      context: ./
      dockerfile: spring-image.dockerfile
    image: leltondev/spring-jwt:latest
    container_name: spring-jwt
    environment:
      PORT: 8081
      POSTGRES_DB: db-spring
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db-spring
    networks:
      jwt:
    ports:
      - 8081:8081
    depends_on:
      - db-spring


networks:
  jwt:
    driver: bridge